name: Bug Report
description: "Submit a new Bug Report"
labels: [bug]
body:
  - type: textarea
    attributes:
      render: shell
      label: "`brew config` output"
    validations:
      required: true
  - type: textarea
    attributes:
      label: What were you trying to do (and why)?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What happened (include all command output)?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      render: shell
      label: Step-by-step reproduction instructions (by running `brew` commands)
    validations:
      required: true
